name: Build Rarimo Web GH Pages
on:
  push:
    branches:
      - 'main'


jobs:
  build:
    name: GH Pages Rarimo Web
    runs-on: ubuntu-latest
    permissions: write-all
    environment: production

    steps:
      - name: Checkout repository and submodules
        uses: actions/checkout@v3
        with:
          submodules: 'recursive'

      - name: 'Extend memory'
        run: |
          export NODE_OPTIONS="--max_old_space_size=16384"

      - name: Set Node.js 18.x
        uses: actions/setup-node@v4
        with:
          node-version: 18.x

      - name: Run package install
        uses: borales/actions-yarn@v4
        with:
          cmd: install

      - name: Run build
        uses: borales/actions-yarn@v4
        with:
          cmd: run build

      - name: Deploy landing to Github Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: dist
